---
title: "'Catch' bir 'Try' deyimi dışında yer alamaz"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 71b83937edb7f42c9bd62d6fba998d95bb047115
ms.sourcegitcommit: 0888d7b24f475c346a3f444de8d83ec1ca7cd234
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 12/22/2018
ms.locfileid: "53776714"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' bir 'Try' deyimi dışında yer alamaz
`Catch` içinde görünmelidir bir `Try...Catch...Finally` deyim bloğu. Ya da gereksiz bir sahip `Catch` deyiminde, `Try` bloğu veya `Catch` deyimi, karşılık gelen sınırları dışında görünür `Try` blok.  
  
 **Hata Kimliği:** BC30380  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1.  Silme `Catch` gereksizdir veya içine yerleştirdiğiniz deyimi bir `Try...Catch...Finally` deyim bloğu.  
  
## <a name="see-also"></a>Ayrıca Bkz.  
 [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
